services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-server
    ports:
      # The RabbitMQ broker port (for NestJS/Apps to connect)
      - "5672:5672"
      # The Management UI port
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq_data: